---
title: "Overview of Ship Power Models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of Ship Power Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(ShipPowerModel)
```


## Introduction
This overview provides a brief description of each of the propulsive ship power models contained in this library. These models span a range of complexity and require a proportional range of vessel-specific inputs. They are broadly categorized as either "Load Factor Models" or "Resistance-Based Models". For an analysis of the differences in the estimates generated by each of these models, see Brown and Aldridge (2019).

Each model described below calculates $P$, the instantaneous propulsive ship power measured in kW.

This overview concludes with a description of the functions available in this package that can be used to assign instantaneous auxiliary and boiler engine loads.

## Load Factor Models
Load factor models estimate power by comparing vessel operating conditions against a set reference conditions and a reference power. These models require a limited set of inputs and are easy to calculate by hand if needed. 

### Propeller Law
The simplest method for estimating ship power is the propeller law, which estimates that propulsion engine operating power varies with the cube of vessel speed. While this method does not account for vessel draft or hull resistance, which can significantly affect ship propulsion load, it relies on few vessel characteristics and is easy to calculate. The only inputs this model requires are the vessel's speed, a reference speed, and the propulsive power needed to maintain the reference speed. This is the model used by the U.S. EPA's vessel emissions modeling prior to the development of the 2017 National Emissions Inventory. The propeller law equation is:
$$ P = \left( \frac{V}{V_{ref}}\right)^3P_{ref} \times SM$$
Where $V$ and $V_{ref}$ are the ship speed and reference speed, $P_{ref}$ is the reference power, and $SM$ is a service margin to account for weather and sea effects.

The function implementing the propeller law is: `calcPropPwr()`. See `vignette("Propeller.Law.Example", package="ShipPowerModel")` for an example using this function.


### Admiralty Formula
The admiralty formula is a simple adaptation of the propeller law that takes a vessel's draft into account. A ship experiences more resistance with a deep draft than with a shallow one. For this model, the additional inputs of operating draft and a reference draft are required. This is model used in the International Maritime Organization's Greenhouse Gas Study. The admiralty formula equation is:
$$ P = \left( \frac{V}{V_{ref}}\right)^3 \left( \frac{T}{T_{ref}}\right)^{\frac{2}{3}} P_{ref} \times SM$$
Where $T$ and $T_{ref}$ are the ship operating draft and reference draft, and the rest of the parameters are the same as the propeller law. Note that when a ship is operating at its reference draft, this equation is identical to the propeller law.

The function implementing the admiralty formula is: `calcAdmPwr()`. See `vignette("Admiralty.Formula.Example", package="ShipPowerModel")` for an example using this function.


## Resistance-Based Models
Resistance-based models use vessel characteristics and operating conditions to estimate the power required to overcome air and water resistance against the vessel's hull. These models also estimate the vessel's efficiency for converting engine power into forward thrust. While these models require more detailed information about each ship than the load factor models, they allow more granular modeling of a vessel's power usage based on its specific design. The general form of these models looks like:
$$ P = \frac{\rho C S V^3}{2\eta}$$
Where $\rho$ is the density of water, $C$ is the vessel's hull resistance coefficient, $S$ is the vessel's hull wetted surface area, and $\eta$ is the vessel's power transmission efficiency. There are two resistance-based models in this package, which differ in how they estimate $C$ and $\eta$.

### Holtrop & Mennen
The Holtrop and Mennen model is one of the first resistance-based models. It was created in 1982 and is based on regression analysis of tank towing data from the Netherlands Ship Model Basin. This model is widely cited in maritime literature. The Holtrop and Mennen model, as implemented by this package, was used by the U.S. EPA to estimate Category 3 commercial marine vessel emissions for the 2017 NEI and the 2016 emissions modeling platform.

The function implementing the Holtrop & Mennen model is: `calcHMPwr()`. See `vignette("HoltropMennen.Example", package="ShipPowerModel")` for an example using this function.

### Kristensen (SHIP_DESMO)
Kristensen's SHIP DESMO model is based on Harvald's 1982 tank towing regression analysis. This method shares several of underlying functions with the Holtrop & Mennen model. A stand alone version of SIP DESMO along with its documentation is hosted and maintained at <https://gitlab.gbar.dtu.dk/oceanwave3d/Ship-Desmo>.

The function implementing the Kristensen model is `calcKristPwr()`. See `vignette("Kristensen.Example", package="ShipPowerModel")` for an example using this function.

## Auxiliary and Boiler Loads
For a full understanding of CMV emissions, auxiliary and boiler engine loads need to be considered in addition to the main engine loads. While auxiliary and boiler loads are not directly derived from vessel activity (such as AIS data), they can be estimated based on ship type, ship subtype, and operating mode. There are functions available in this package for assigning each of these: 

* `calcShipType()` is used to standardize ship types
* `calcSubType()` is used to assign ship subtypes based on vessel size parameters (such as number of TEUs, tonnage, or number of passengers)
* `calcOperatingMode()` is used to assign operating modes (such as at berth, maneuvering, in transit, or at anchor) based on ship speed, main engine load factor (derived from any of the above ship power models), and geospatial information (e.g., is the vessel in a berth or anchorage area?).

With each of these in hand, `calcAuxBoilerLoad()` is used to assign instantaneous auxiliary and boiler engine loads.

## References

Brown, I. N. and Aldridge, M. F. 2019. "Power models and average ship parameter effects on marine emissions inventories." JAWMA 69, 6: 752–763. <https://doi.org/10.1080/10962247.2019.1580229> 

EPA. 2009. "Regulatory impact analysis: Control of emissions air pollution from category 3 marine diesel engines." Ann Arbor, MI: Office of Transportation and Air Quality. US Environmental Protection Agency. <https://nepis.epa.gov/Exe/ZyPURL.cgi?Dockey=P1005ZGH.TXT>

International Maritime Organization. 2014. "Third IMO GHG study 2014 - Final report." London: International Maritime Organization

Harvald, S. A. 1983. "Resistance and propulsion of ships". New York: Wiley Interscience

Holtrop, J. and Mennen G. G. J. 1982. "An approximate power prediction method." International Shipbuilding Progress 29: 166-170

Kristensen, H. O. "Ship-Desmo-Tool." <https://gitlab.gbar.dtu.dk/oceanwave3d/Ship-Desmo>

